version: 2

seeds:
  - name: raw_customers
    description: "Seed contendo a lista de clientes bruta, utilizada na camada RAW."
    config:
      column_types:
        customer_id: text
        full_name: text
        email: text
        phone: text
        zipcode: text
        created_at: timestamp
  - name: raw_geo_zipcode
    description: "Seed contendo referencias de geolocalização, utilizada na camada RAW."
    config:
      column_types:
        zipcode: text
        city: text
        state: text
        region: text
