demo_dbt:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: my_pwd
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: new_user
    prd:
      dbname: postgres
      host: http://xpto.server
      pass: my_pwd
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: new_user
  target: dev
study_dbt:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: my_pwd
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: new_user
  target: dev
